package webhook

type IterationCreateEvent struct {
	Event               EventType `json:"event,omitempty"`
	EventFrom           string    `json:"event_from,omitempty"`
	Referer             string    `json:"referer,omitempty"`
	WorkspaceID         string    `json:"workspace_id,omitempty"`
	CurrentUser         string    `json:"current_user,omitempty"`
	ID                  string    `json:"id,omitempty"`
	Name                string    `json:"name,omitempty"`
	Description         string    `json:"description,omitempty"`
	MarkdownDescription string    `json:"markdown_description,omitempty"`
	DescriptionType     string    `json:"description_type,omitempty"`
	EntityType          string    `json:"entity_type,omitempty"`
	WorkitemTypeID      string    `json:"workitem_type_id,omitempty"`
	AttachmentToken     string    `json:"attachment_token,omitempty"`
	CrucialMoment       string    `json:"crucial_moment,omitempty"`
	StartDate           string    `json:"startdate,omitempty"`
	EndDate             string    `json:"enddate,omitempty"`
	TemplatedID         string    `json:"templated_id,omitempty"`
	Creator             string    `json:"creator,omitempty"`
	Secret              string    `json:"secret,omitempty"`
	RioToken            string    `json:"rio_token,omitempty"`
	DevProxyHost        string    `json:"devproxy_host,omitempty"`
	QueueID             string    `json:"queue_id,omitempty"`
	EventID             string    `json:"event_id,omitempty"`
	Created             string    `json:"created,omitempty"`
}

type IterationUpdateEvent struct {
	Event                   EventType `json:"event,omitempty"`
	EventFrom               string    `json:"event_from,omitempty"`
	Referer                 string    `json:"referer,omitempty"`
	WorkspaceID             string    `json:"workspace_id,omitempty"`
	CurrentUser             string    `json:"current_user,omitempty"`
	ID                      string    `json:"id,omitempty"`
	OldID                   string    `json:"old_id,omitempty"`
	OldSort                 string    `json:"old_sort,omitempty"`
	OldWorkitemTypeID       string    `json:"old_workitem_type_id,omitempty"`
	OldEntityType           string    `json:"old_entity_type,omitempty"`
	OldReleaseID            string    `json:"old_release_id,omitempty"`
	OldWorkspaceID          string    `json:"old_workspace_id,omitempty"`
	OldPlanAppID            string    `json:"old_plan_app_id,omitempty"`
	OldName                 string    `json:"old_name,omitempty"`
	OldDescription          string    `json:"old_description,omitempty"`
	OldMarkdownDescription  string    `json:"old_markdown_description,omitempty"`
	OldDescriptionType      string    `json:"old_description_type,omitempty"`
	OldStartDate            string    `json:"old_startdate,omitempty"`
	OldStories              string    `json:"old_stories,omitempty"`
	OldEndDate              string    `json:"old_enddate,omitempty"`
	OldBugs                 string    `json:"old_bugs,omitempty"`
	OldEffortTotalCompleted string    `json:"old_effort_total_completed,omitempty"`
	OldEffortTotal          string    `json:"old_effort_total,omitempty"`
	OldDuration             string    `json:"old_duration,omitempty"`
	OldVelocity             string    `json:"old_velocity,omitempty"`
	OldCreator              string    `json:"old_creator,omitempty"`
	OldModifier             string    `json:"old_modifier,omitempty"`
	OldColor                string    `json:"old_color,omitempty"`
	OldIcon                 string    `json:"old_icon,omitempty"`
	OldLine                 string    `json:"old_line,omitempty"`
	OldCreated              string    `json:"old_created,omitempty"`
	OldModified             string    `json:"old_modified,omitempty"`
	OldParentID             string    `json:"old_parent_id,omitempty"`
	OldAncestorID           string    `json:"old_ancestor_id,omitempty"`
	OldPath                 string    `json:"old_path,omitempty"`
	OldCompleted            string    `json:"old_completed,omitempty"`
	OldReleaseOwner         string    `json:"old_releaseowner,omitempty"`
	OldLaunchDate           string    `json:"old_launchdate,omitempty"`
	OldNotice               string    `json:"old_notice,omitempty"`
	OldStatus               string    `json:"old_status,omitempty"`
	OldIsDelay              string    `json:"old_isdelay,omitempty"`
	OldReleaseName          string    `json:"old_releasename,omitempty"`
	OldEstimatedPoints      string    `json:"old_estimated_points,omitempty"`
	OldTemplatedID          string    `json:"old_templated_id,omitempty"`
	OldIsTop                string    `json:"old_is_top,omitempty"`
	OldTopTime              string    `json:"old_top_time,omitempty"`
	OldDashboardSetting     string    `json:"old_dashboard_setting,omitempty"`
	OldCreatedFrom          string    `json:"old_created_from,omitempty"`
	OldLockInfo             string    `json:"old_lock_info,omitempty"`
	OldLocker               string    `json:"old_locker,omitempty"`
	OldCrucialMoment        string    `json:"old_crucial_moment,omitempty"`
	OldLabel                string    `json:"old_label,omitempty"`
	OldCustomField1         string    `json:"old_custom_field_1,omitempty"`
	OldCustomField2         string    `json:"old_custom_field_2,omitempty"`
	OldCustomField3         string    `json:"old_custom_field_3,omitempty"`
	OldCustomField4         string    `json:"old_custom_field_4,omitempty"`
	OldCustomField5         string    `json:"old_custom_field_5,omitempty"`
	OldCustomField6         string    `json:"old_custom_field_6,omitempty"`
	OldCustomField7         string    `json:"old_custom_field_7,omitempty"`
	OldCustomField8         string    `json:"old_custom_field_8,omitempty"`
	OldCustomField9         string    `json:"old_custom_field_9,omitempty"`
	OldCustomField10        string    `json:"old_custom_field_10,omitempty"`
	OldCustomField11        string    `json:"old_custom_field_11,omitempty"`
	OldCustomField12        string    `json:"old_custom_field_12,omitempty"`
	OldCustomField13        string    `json:"old_custom_field_13,omitempty"`
	OldCustomField14        string    `json:"old_custom_field_14,omitempty"`
	OldCustomField15        string    `json:"old_custom_field_15,omitempty"`
	OldCustomField16        string    `json:"old_custom_field_16,omitempty"`
	OldCustomField17        string    `json:"old_custom_field_17,omitempty"`
	OldCustomField18        string    `json:"old_custom_field_18,omitempty"`
	OldCustomField19        string    `json:"old_custom_field_19,omitempty"`
	OldCustomField20        string    `json:"old_custom_field_20,omitempty"`
	OldCustomField21        string    `json:"old_custom_field_21,omitempty"`
	OldCustomField22        string    `json:"old_custom_field_22,omitempty"`
	OldCustomField23        string    `json:"old_custom_field_23,omitempty"`
	OldCustomField24        string    `json:"old_custom_field_24,omitempty"`
	OldCustomField25        string    `json:"old_custom_field_25,omitempty"`
	OldCustomField26        string    `json:"old_custom_field_26,omitempty"`
	OldCustomField27        string    `json:"old_custom_field_27,omitempty"`
	OldCustomField28        string    `json:"old_custom_field_28,omitempty"`
	OldCustomField29        string    `json:"old_custom_field_29,omitempty"`
	OldCustomField30        string    `json:"old_custom_field_30,omitempty"`
	OldCustomField31        string    `json:"old_custom_field_31,omitempty"`
	OldCustomField32        string    `json:"old_custom_field_32,omitempty"`
	OldCustomField33        string    `json:"old_custom_field_33,omitempty"`
	OldCustomField34        string    `json:"old_custom_field_34,omitempty"`
	OldCustomField35        string    `json:"old_custom_field_35,omitempty"`
	OldCustomField36        string    `json:"old_custom_field_36,omitempty"`
	OldCustomField37        string    `json:"old_custom_field_37,omitempty"`
	OldCustomField38        string    `json:"old_custom_field_38,omitempty"`
	OldCustomField39        string    `json:"old_custom_field_39,omitempty"`
	OldCustomField40        string    `json:"old_custom_field_40,omitempty"`
	OldCustomField41        string    `json:"old_custom_field_41,omitempty"`
	OldCustomField42        string    `json:"old_custom_field_42,omitempty"`
	OldCustomField43        string    `json:"old_custom_field_43,omitempty"`
	OldCustomField44        string    `json:"old_custom_field_44,omitempty"`
	OldCustomField45        string    `json:"old_custom_field_45,omitempty"`
	OldCustomField46        string    `json:"old_custom_field_46,omitempty"`
	OldCustomField47        string    `json:"old_custom_field_47,omitempty"`
	OldCustomField48        string    `json:"old_custom_field_48,omitempty"`
	OldCustomField49        string    `json:"old_custom_field_49,omitempty"`
	OldCustomField50        string    `json:"old_custom_field_50,omitempty"`
	NewID                   string    `json:"new_id,omitempty"`
	NewSort                 string    `json:"new_sort,omitempty"`
	NewWorkitemTypeID       string    `json:"new_workitem_type_id,omitempty"`
	NewEntityType           string    `json:"new_entity_type,omitempty"`
	NewReleaseID            string    `json:"new_release_id,omitempty"`
	NewWorkspaceID          string    `json:"new_workspace_id,omitempty"`
	NewPlanAppID            string    `json:"new_plan_app_id,omitempty"`
	NewName                 string    `json:"new_name,omitempty"`
	NewDescription          string    `json:"new_description,omitempty"`
	NewMarkdownDescription  string    `json:"new_markdown_description,omitempty"`
	NewDescriptionType      string    `json:"new_description_type,omitempty"`
	NewStartDate            string    `json:"new_startdate,omitempty"`
	NewStories              string    `json:"new_stories,omitempty"`
	NewEndDate              string    `json:"new_enddate,omitempty"`
	NewBugs                 string    `json:"new_bugs,omitempty"`
	NewEffortTotalCompleted string    `json:"new_effort_total_completed,omitempty"`
	NewEffortTotal          string    `json:"new_effort_total,omitempty"`
	NewDuration             string    `json:"new_duration,omitempty"`
	NewVelocity             string    `json:"new_velocity,omitempty"`
	NewCreator              string    `json:"new_creator,omitempty"`
	NewModifier             string    `json:"new_modifier,omitempty"`
	NewColor                string    `json:"new_color,omitempty"`
	NewIcon                 string    `json:"new_icon,omitempty"`
	NewLine                 string    `json:"new_line,omitempty"`
	NewCreated              string    `json:"new_created,omitempty"`
	NewModified             string    `json:"new_modified,omitempty"`
	NewParentID             string    `json:"new_parent_id,omitempty"`
	NewAncestorID           string    `json:"new_ancestor_id,omitempty"`
	NewPath                 string    `json:"new_path,omitempty"`
	NewCompleted            string    `json:"new_completed,omitempty"`
	NewReleaseOwner         string    `json:"new_releaseowner,omitempty"`
	NewLaunchDate           string    `json:"new_launchdate,omitempty"`
	NewNotice               string    `json:"new_notice,omitempty"`
	NewStatus               string    `json:"new_status,omitempty"`
	NewIsDelay              string    `json:"new_isdelay,omitempty"`
	NewReleaseName          string    `json:"new_releasename,omitempty"`
	NewEstimatedPoints      string    `json:"new_estimated_points,omitempty"`
	NewTemplatedID          string    `json:"new_templated_id,omitempty"`
	NewIsTop                string    `json:"new_is_top,omitempty"`
	NewTopTime              string    `json:"new_top_time,omitempty"`
	NewDashboardSetting     string    `json:"new_dashboard_setting,omitempty"`
	NewCreatedFrom          string    `json:"new_created_from,omitempty"`
	NewLockInfo             string    `json:"new_lock_info,omitempty"`
	NewLocker               string    `json:"new_locker,omitempty"`
	NewCrucialMoment        string    `json:"new_crucial_moment,omitempty"`
	NewLabel                string    `json:"new_label,omitempty"`
	NewCustomField1         string    `json:"new_custom_field_1,omitempty"`
	NewCustomField2         string    `json:"new_custom_field_2,omitempty"`
	NewCustomField3         string    `json:"new_custom_field_3,omitempty"`
	NewCustomField4         string    `json:"new_custom_field_4,omitempty"`
	NewCustomField5         string    `json:"new_custom_field_5,omitempty"`
	NewCustomField6         string    `json:"new_custom_field_6,omitempty"`
	NewCustomField7         string    `json:"new_custom_field_7,omitempty"`
	NewCustomField8         string    `json:"new_custom_field_8,omitempty"`
	NewCustomField9         string    `json:"new_custom_field_9,omitempty"`
	NewCustomField10        string    `json:"new_custom_field_10,omitempty"`
	NewCustomField11        string    `json:"new_custom_field_11,omitempty"`
	NewCustomField12        string    `json:"new_custom_field_12,omitempty"`
	NewCustomField13        string    `json:"new_custom_field_13,omitempty"`
	NewCustomField14        string    `json:"new_custom_field_14,omitempty"`
	NewCustomField15        string    `json:"new_custom_field_15,omitempty"`
	NewCustomField16        string    `json:"new_custom_field_16,omitempty"`
	NewCustomField17        string    `json:"new_custom_field_17,omitempty"`
	NewCustomField18        string    `json:"new_custom_field_18,omitempty"`
	NewCustomField19        string    `json:"new_custom_field_19,omitempty"`
	NewCustomField20        string    `json:"new_custom_field_20,omitempty"`
	NewCustomField21        string    `json:"new_custom_field_21,omitempty"`
	NewCustomField22        string    `json:"new_custom_field_22,omitempty"`
	NewCustomField23        string    `json:"new_custom_field_23,omitempty"`
	NewCustomField24        string    `json:"new_custom_field_24,omitempty"`
	NewCustomField25        string    `json:"new_custom_field_25,omitempty"`
	NewCustomField26        string    `json:"new_custom_field_26,omitempty"`
	NewCustomField27        string    `json:"new_custom_field_27,omitempty"`
	NewCustomField28        string    `json:"new_custom_field_28,omitempty"`
	NewCustomField29        string    `json:"new_custom_field_29,omitempty"`
	NewCustomField30        string    `json:"new_custom_field_30,omitempty"`
	NewCustomField31        string    `json:"new_custom_field_31,omitempty"`
	NewCustomField32        string    `json:"new_custom_field_32,omitempty"`
	NewCustomField33        string    `json:"new_custom_field_33,omitempty"`
	NewCustomField34        string    `json:"new_custom_field_34,omitempty"`
	NewCustomField35        string    `json:"new_custom_field_35,omitempty"`
	NewCustomField36        string    `json:"new_custom_field_36,omitempty"`
	NewCustomField37        string    `json:"new_custom_field_37,omitempty"`
	NewCustomField38        string    `json:"new_custom_field_38,omitempty"`
	NewCustomField39        string    `json:"new_custom_field_39,omitempty"`
	NewCustomField40        string    `json:"new_custom_field_40,omitempty"`
	NewCustomField41        string    `json:"new_custom_field_41,omitempty"`
	NewCustomField42        string    `json:"new_custom_field_42,omitempty"`
	NewCustomField43        string    `json:"new_custom_field_43,omitempty"`
	NewCustomField44        string    `json:"new_custom_field_44,omitempty"`
	NewCustomField45        string    `json:"new_custom_field_45,omitempty"`
	NewCustomField46        string    `json:"new_custom_field_46,omitempty"`
	NewCustomField47        string    `json:"new_custom_field_47,omitempty"`
	NewCustomField48        string    `json:"new_custom_field_48,omitempty"`
	NewCustomField49        string    `json:"new_custom_field_49,omitempty"`
	NewCustomField50        string    `json:"new_custom_field_50,omitempty"`
	ChangeFields            string    `json:"change_fields,omitempty"`
	Secret                  string    `json:"secret,omitempty"`
	RioToken                string    `json:"rio_token,omitempty"`
	DevProxyHost            string    `json:"devproxy_host,omitempty"`
	QueueID                 string    `json:"queue_id,omitempty"`
	EventID                 string    `json:"event_id,omitempty"`
	Created                 string    `json:"created,omitempty"`
}

type IterationDeleteEvent struct {
	Event        EventType `json:"event,omitempty"`
	EventFrom    string    `json:"event_from,omitempty"`
	Referer      string    `json:"referer,omitempty"`
	WorkspaceID  string    `json:"workspace_id,omitempty"`
	CurrentUser  string    `json:"current_user,omitempty"`
	ID           string    `json:"id,omitempty"`
	OpType       string    `json:"op_type,omitempty"`
	Secret       string    `json:"secret,omitempty"`
	RioToken     string    `json:"rio_token,omitempty"`
	DevProxyHost string    `json:"devproxy_host,omitempty"`
	QueueID      string    `json:"queue_id,omitempty"`
	EventID      string    `json:"event_id,omitempty"`
	Created      string    `json:"created,omitempty"`
}
