package webhook

type BugCreateEvent struct {
	Event            EventType `json:"event,omitempty"`
	EventFrom        string    `json:"event_from,omitempty"`
	Referer          string    `json:"referer,omitempty"`
	WorkspaceID      string    `json:"workspace_id,omitempty"`
	CurrentUser      string    `json:"current_user,omitempty"`
	ID               string    `json:"id,omitempty"`
	Title            string    `json:"title,omitempty"`
	IssueID          string    `json:"issue_id,omitempty"`
	IsNewStatus      string    `json:"is_new_status,omitempty"`
	IsReplicate      string    `json:"is_replicate,omitempty"`
	CreateLink       string    `json:"create_link,omitempty"`
	IsJenkins        string    `json:"is_jenkins,omitempty"`
	TemplateID       string    `json:"template_id,omitempty"`
	Description      string    `json:"description,omitempty"`
	IterationID      string    `json:"iteration_id,omitempty"`
	Severity         string    `json:"severity,omitempty"`
	Priority         string    `json:"priority,omitempty"`
	CustomFieldOne   string    `json:"custom_field_one,omitempty"`
	CustomFieldThree string    `json:"custom_field_three,omitempty"`
	CustomFieldFour  string    `json:"custom_field_four,omitempty"`
	CustomField6     string    `json:"custom_field_6,omitempty"`
	CurrentOwner     string    `json:"current_owner,omitempty"`
	CC               string    `json:"cc,omitempty"`
	De               string    `json:"de,omitempty"`
	Te               string    `json:"te,omitempty"`
	Platform         string    `json:"platform,omitempty"`
	BugType          string    `json:"bugtype,omitempty"`
	OriginPhase      string    `json:"originphase,omitempty"`
	Source           string    `json:"source,omitempty"`
	DescriptionType  string    `json:"description_type,omitempty"`
	ProjectID        string    `json:"project_id,omitempty"`
	IsDraft          string    `json:"is_draft,omitempty"`
	Begin            string    `json:"begin,omitempty"`
	Due              string    `json:"due,omitempty"`
	Status           string    `json:"status,omitempty"`
	Reporter         string    `json:"reporter,omitempty"`
	Flows            string    `json:"flows,omitempty"`
	Resolution       string    `json:"resolution,omitempty"`
	Resolved         string    `json:"resolved,omitempty"`
	Closed           string    `json:"closed,omitempty"`
	InProgressTime   string    `json:"in_progress_time,omitempty"`
	VerifyTime       string    `json:"verify_time,omitempty"`
	RejectTime       string    `json:"reject_time,omitempty"`
	AuditTime        string    `json:"audit_time,omitempty"`
	SuspendTime      string    `json:"suspend_time,omitempty"`
	Secret           string    `json:"secret,omitempty"`
	RioToken         string    `json:"rio_token,omitempty"`
	DevProxyHost     string    `json:"devproxy_host,omitempty"`
	QueueID          string    `json:"queue_id,omitempty"`
	EventID          string    `json:"event_id,omitempty"`
	Created          string    `json:"created,omitempty"`
}

type BugUpdateEvent struct {
	Event                  EventType `json:"event,omitempty"`
	EventFrom              string    `json:"event_from,omitempty"`
	Referer                string    `json:"referer,omitempty"`
	WorkspaceID            string    `json:"workspace_id,omitempty"`
	CurrentUser            string    `json:"current_user,omitempty"`
	ID                     string    `json:"id,omitempty"`
	OldID                  string    `json:"old_id,omitempty"`
	OldSecretRootID        string    `json:"old_secret_root_id,omitempty"`
	OldSid                 string    `json:"old_sid,omitempty"`
	OldProjectID           string    `json:"old_project_id,omitempty"`
	OldParentID            string    `json:"old_parent_id,omitempty"`
	OldTitle               string    `json:"old_title,omitempty"`
	OldDescription         string    `json:"old_description,omitempty"`
	OldMarkdownDescription string    `json:"old_markdown_description,omitempty"`
	OldDescriptionType     string    `json:"old_description_type,omitempty"`
	OldModule              string    `json:"old_module,omitempty"`
	OldMilestone           string    `json:"old_milestone,omitempty"`
	OldReporter            string    `json:"old_reporter,omitempty"`
	OldDeadline            string    `json:"old_deadline,omitempty"`
	OldCreated             string    `json:"old_created,omitempty"`
	OldResolved            string    `json:"old_resolved,omitempty"`
	OldClosed              string    `json:"old_closed,omitempty"`
	OldModified            string    `json:"old_modified,omitempty"`
	OldLastModify          string    `json:"old_lastmodify,omitempty"`
	OldAuditer             string    `json:"old_auditer,omitempty"`
	OldDe                  string    `json:"old_de,omitempty"`
	OldTe                  string    `json:"old_te,omitempty"`
	OldConfirmer           string    `json:"old_confirmer,omitempty"`
	OldCurrentOwner        string    `json:"old_current_owner,omitempty"`
	OldParticipator        string    `json:"old_participator,omitempty"`
	OldCloser              string    `json:"old_closer,omitempty"`
	OldStatus              string    `json:"old_status,omitempty"`
	OldResolution          string    `json:"old_resolution,omitempty"`
	OldPriority            string    `json:"old_priority,omitempty"`
	OldSeverity            string    `json:"old_severity,omitempty"`
	OldPlatform            string    `json:"old_platform,omitempty"`
	OldOs                  string    `json:"old_os,omitempty"`
	OldTestMode            string    `json:"old_testmode,omitempty"`
	OldTestType            string    `json:"old_testtype,omitempty"`
	OldTestPhase           string    `json:"old_testphase,omitempty"`
	OldSource              string    `json:"old_source,omitempty"`
	OldFrequency           string    `json:"old_frequency,omitempty"`
	OldCc                  string    `json:"old_cc,omitempty"`
	OldEstimate            string    `json:"old_estimate,omitempty"`
	OldFlows               string    `json:"old_flows,omitempty"`
	OldVersionReport       string    `json:"old_version_report,omitempty"`
	OldVersionTest         string    `json:"old_version_test,omitempty"`
	OldVersionFix          string    `json:"old_version_fix,omitempty"`
	OldVersionClose        string    `json:"old_version_close,omitempty"`
	OldDelayed             string    `json:"old_delayed,omitempty"`
	OldCustomFieldOne      string    `json:"old_custom_field_one,omitempty"`
	OldCustomFieldTwo      string    `json:"old_custom_field_two,omitempty"`
	OldCustomFieldThree    string    `json:"old_custom_field_three,omitempty"`
	OldCustomFieldFour     string    `json:"old_custom_field_four,omitempty"`
	OldCustomFieldFive     string    `json:"old_custom_field_five,omitempty"`
	OldRegressionNumber    string    `json:"old_regression_number,omitempty"`
	OldIssueID             string    `json:"old_issue_id,omitempty"`
	OldSupportID           string    `json:"old_support_id,omitempty"`
	OldSupportForumID      string    `json:"old_support_forum_id,omitempty"`
	OldCreatedFrom         string    `json:"old_created_from,omitempty"`
	OldBaselineFind        string    `json:"old_baseline_find,omitempty"`
	OldBaselineJoin        string    `json:"old_baseline_join,omitempty"`
	OldBaselineClose       string    `json:"old_baseline_close,omitempty"`
	OldTicketID            string    `json:"old_ticket_id,omitempty"`
	OldStoryID             string    `json:"old_story_id,omitempty"`
	OldBaselineTest        string    `json:"old_baseline_test,omitempty"`
	OldOriginPhase         string    `json:"old_originphase,omitempty"`
	OldSourcePhase         string    `json:"old_sourcephase,omitempty"`
	OldBugType             string    `json:"old_bugtype,omitempty"`
	OldFeature             string    `json:"old_feature,omitempty"`
	OldInProgressTime      string    `json:"old_in_progress_time,omitempty"`
	OldVerifyTime          string    `json:"old_verify_time,omitempty"`
	OldRejectTime          string    `json:"old_reject_time,omitempty"`
	OldReopenTime          string    `json:"old_reopen_time,omitempty"`
	OldAuditTime           string    `json:"old_audit_time,omitempty"`
	OldSuspendTime         string    `json:"old_suspend_time,omitempty"`
	OldAssignedTime        string    `json:"old_assigned_time,omitempty"`
	OldIterationID         string    `json:"old_iteration_id,omitempty"`
	OldCustomField6        string    `json:"old_custom_field_6,omitempty"`
	OldCustomField7        string    `json:"old_custom_field_7,omitempty"`
	OldCustomField8        string    `json:"old_custom_field_8,omitempty"`
	OldCustomField9        string    `json:"old_custom_field_9,omitempty"`
	OldCustomField10       string    `json:"old_custom_field_10,omitempty"`
	OldCustomField11       string    `json:"old_custom_field_11,omitempty"`
	OldCustomField12       string    `json:"old_custom_field_12,omitempty"`
	OldCustomField13       string    `json:"old_custom_field_13,omitempty"`
	OldCustomField14       string    `json:"old_custom_field_14,omitempty"`
	OldCustomField15       string    `json:"old_custom_field_15,omitempty"`
	OldCustomField16       string    `json:"old_custom_field_16,omitempty"`
	OldCustomField17       string    `json:"old_custom_field_17,omitempty"`
	OldCustomField18       string    `json:"old_custom_field_18,omitempty"`
	OldCustomField19       string    `json:"old_custom_field_19,omitempty"`
	OldCustomField20       string    `json:"old_custom_field_20,omitempty"`
	OldCustomField21       string    `json:"old_custom_field_21,omitempty"`
	OldCustomField22       string    `json:"old_custom_field_22,omitempty"`
	OldCustomField23       string    `json:"old_custom_field_23,omitempty"`
	OldCustomField24       string    `json:"old_custom_field_24,omitempty"`
	OldCustomField25       string    `json:"old_custom_field_25,omitempty"`
	OldCustomField26       string    `json:"old_custom_field_26,omitempty"`
	OldCustomField27       string    `json:"old_custom_field_27,omitempty"`
	OldCustomField28       string    `json:"old_custom_field_28,omitempty"`
	OldCustomField29       string    `json:"old_custom_field_29,omitempty"`
	OldCustomField30       string    `json:"old_custom_field_30,omitempty"`
	OldCustomField31       string    `json:"old_custom_field_31,omitempty"`
	OldCustomField32       string    `json:"old_custom_field_32,omitempty"`
	OldCustomField33       string    `json:"old_custom_field_33,omitempty"`
	OldCustomField34       string    `json:"old_custom_field_34,omitempty"`
	OldCustomField35       string    `json:"old_custom_field_35,omitempty"`
	OldCustomField36       string    `json:"old_custom_field_36,omitempty"`
	OldCustomField37       string    `json:"old_custom_field_37,omitempty"`
	OldCustomField38       string    `json:"old_custom_field_38,omitempty"`
	OldCustomField39       string    `json:"old_custom_field_39,omitempty"`
	OldCustomField40       string    `json:"old_custom_field_40,omitempty"`
	OldCustomField41       string    `json:"old_custom_field_41,omitempty"`
	OldCustomField42       string    `json:"old_custom_field_42,omitempty"`
	OldCustomField43       string    `json:"old_custom_field_43,omitempty"`
	OldCustomField44       string    `json:"old_custom_field_44,omitempty"`
	OldCustomField45       string    `json:"old_custom_field_45,omitempty"`
	OldCustomField46       string    `json:"old_custom_field_46,omitempty"`
	OldCustomField47       string    `json:"old_custom_field_47,omitempty"`
	OldCustomField48       string    `json:"old_custom_field_48,omitempty"`
	OldCustomField49       string    `json:"old_custom_field_49,omitempty"`
	OldCustomField50       string    `json:"old_custom_field_50,omitempty"`
	OldCustomField51       string    `json:"old_custom_field_51,omitempty"`
	OldCustomField52       string    `json:"old_custom_field_52,omitempty"`
	OldCustomField53       string    `json:"old_custom_field_53,omitempty"`
	OldCustomField54       string    `json:"old_custom_field_54,omitempty"`
	OldCustomField55       string    `json:"old_custom_field_55,omitempty"`
	OldCustomField56       string    `json:"old_custom_field_56,omitempty"`
	OldCustomField57       string    `json:"old_custom_field_57,omitempty"`
	OldCustomField58       string    `json:"old_custom_field_58,omitempty"`
	OldCustomField59       string    `json:"old_custom_field_59,omitempty"`
	OldCustomField60       string    `json:"old_custom_field_60,omitempty"`
	OldCustomField61       string    `json:"old_custom_field_61,omitempty"`
	OldCustomField62       string    `json:"old_custom_field_62,omitempty"`
	OldCustomField63       string    `json:"old_custom_field_63,omitempty"`
	OldCustomField64       string    `json:"old_custom_field_64,omitempty"`
	OldCustomField65       string    `json:"old_custom_field_65,omitempty"`
	OldCustomField66       string    `json:"old_custom_field_66,omitempty"`
	OldCustomField67       string    `json:"old_custom_field_67,omitempty"`
	OldCustomField68       string    `json:"old_custom_field_68,omitempty"`
	OldCustomField69       string    `json:"old_custom_field_69,omitempty"`
	OldCustomField70       string    `json:"old_custom_field_70,omitempty"`
	OldCustomField71       string    `json:"old_custom_field_71,omitempty"`
	OldCustomField72       string    `json:"old_custom_field_72,omitempty"`
	OldCustomField73       string    `json:"old_custom_field_73,omitempty"`
	OldCustomField74       string    `json:"old_custom_field_74,omitempty"`
	OldCustomField75       string    `json:"old_custom_field_75,omitempty"`
	OldCustomField76       string    `json:"old_custom_field_76,omitempty"`
	OldCustomField77       string    `json:"old_custom_field_77,omitempty"`
	OldCustomField78       string    `json:"old_custom_field_78,omitempty"`
	OldCustomField79       string    `json:"old_custom_field_79,omitempty"`
	OldCustomField80       string    `json:"old_custom_field_80,omitempty"`
	OldCustomField81       string    `json:"old_custom_field_81,omitempty"`
	OldCustomField82       string    `json:"old_custom_field_82,omitempty"`
	OldCustomField83       string    `json:"old_custom_field_83,omitempty"`
	OldCustomField84       string    `json:"old_custom_field_84,omitempty"`
	OldCustomField85       string    `json:"old_custom_field_85,omitempty"`
	OldCustomField86       string    `json:"old_custom_field_86,omitempty"`
	OldCustomField87       string    `json:"old_custom_field_87,omitempty"`
	OldCustomField88       string    `json:"old_custom_field_88,omitempty"`
	OldCustomField89       string    `json:"old_custom_field_89,omitempty"`
	OldCustomField90       string    `json:"old_custom_field_90,omitempty"`
	OldCustomField91       string    `json:"old_custom_field_91,omitempty"`
	OldCustomField92       string    `json:"old_custom_field_92,omitempty"`
	OldCustomField93       string    `json:"old_custom_field_93,omitempty"`
	OldCustomField94       string    `json:"old_custom_field_94,omitempty"`
	OldCustomField95       string    `json:"old_custom_field_95,omitempty"`
	OldCustomField96       string    `json:"old_custom_field_96,omitempty"`
	OldCustomField97       string    `json:"old_custom_field_97,omitempty"`
	OldCustomField98       string    `json:"old_custom_field_98,omitempty"`
	OldCustomField99       string    `json:"old_custom_field_99,omitempty"`
	OldCustomField100      string    `json:"old_custom_field_100,omitempty"`
	OldCustomPlanField1    string    `json:"old_custom_plan_field_1,omitempty"`
	OldCustomPlanField2    string    `json:"old_custom_plan_field_2,omitempty"`
	OldCustomPlanField3    string    `json:"old_custom_plan_field_3,omitempty"`
	OldCustomPlanField4    string    `json:"old_custom_plan_field_4,omitempty"`
	OldCustomPlanField5    string    `json:"old_custom_plan_field_5,omitempty"`
	OldCustomPlanField6    string    `json:"old_custom_plan_field_6,omitempty"`
	OldCustomPlanField7    string    `json:"old_custom_plan_field_7,omitempty"`
	OldCustomPlanField8    string    `json:"old_custom_plan_field_8,omitempty"`
	OldCustomPlanField9    string    `json:"old_custom_plan_field_9,omitempty"`
	OldCustomPlanField10   string    `json:"old_custom_plan_field_10,omitempty"`
	OldTemplateID          string    `json:"old_template_id,omitempty"`
	OldBegin               string    `json:"old_begin,omitempty"`
	OldDue                 string    `json:"old_due,omitempty"`
	OldReleaseID           string    `json:"old_release_id,omitempty"`
	OldFixer               string    `json:"old_fixer,omitempty"`
	OldFollower            string    `json:"old_follower,omitempty"`
	OldSyncType            string    `json:"old_sync_type,omitempty"`
	OldLabel               string    `json:"old_label,omitempty"`
	OldEffort              string    `json:"old_effort,omitempty"`
	OldEffortCompleted     string    `json:"old_effort_completed,omitempty"`
	OldExceed              string    `json:"old_exceed,omitempty"`
	OldRemain              string    `json:"old_remain,omitempty"`
	OldProgress            string    `json:"old_progress,omitempty"`
	OldSize                string    `json:"old_size,omitempty"`
	OldCustomField101      string    `json:"old_custom_field_101,omitempty"`
	OldCustomField102      string    `json:"old_custom_field_102,omitempty"`
	OldCustomField103      string    `json:"old_custom_field_103,omitempty"`
	OldCustomField104      string    `json:"old_custom_field_104,omitempty"`
	OldCustomField105      string    `json:"old_custom_field_105,omitempty"`
	OldCustomField106      string    `json:"old_custom_field_106,omitempty"`
	OldCustomField107      string    `json:"old_custom_field_107,omitempty"`
	OldCustomField108      string    `json:"old_custom_field_108,omitempty"`
	OldCustomField109      string    `json:"old_custom_field_109,omitempty"`
	OldCustomField110      string    `json:"old_custom_field_110,omitempty"`
	OldCustomField111      string    `json:"old_custom_field_111,omitempty"`
	OldCustomField112      string    `json:"old_custom_field_112,omitempty"`
	OldCustomField113      string    `json:"old_custom_field_113,omitempty"`
	OldCustomField114      string    `json:"old_custom_field_114,omitempty"`
	OldCustomField115      string    `json:"old_custom_field_115,omitempty"`
	OldCustomField116      string    `json:"old_custom_field_116,omitempty"`
	OldCustomField117      string    `json:"old_custom_field_117,omitempty"`
	OldCustomField118      string    `json:"old_custom_field_118,omitempty"`
	OldCustomField119      string    `json:"old_custom_field_119,omitempty"`
	OldCustomField120      string    `json:"old_custom_field_120,omitempty"`
	OldCustomField121      string    `json:"old_custom_field_121,omitempty"`
	OldCustomField122      string    `json:"old_custom_field_122,omitempty"`
	OldCustomField123      string    `json:"old_custom_field_123,omitempty"`
	OldCustomField124      string    `json:"old_custom_field_124,omitempty"`
	OldCustomField125      string    `json:"old_custom_field_125,omitempty"`
	OldCustomField126      string    `json:"old_custom_field_126,omitempty"`
	OldCustomField127      string    `json:"old_custom_field_127,omitempty"`
	OldCustomField128      string    `json:"old_custom_field_128,omitempty"`
	OldCustomField129      string    `json:"old_custom_field_129,omitempty"`
	OldCustomField130      string    `json:"old_custom_field_130,omitempty"`
	OldCustomField131      string    `json:"old_custom_field_131,omitempty"`
	OldCustomField132      string    `json:"old_custom_field_132,omitempty"`
	OldCustomField133      string    `json:"old_custom_field_133,omitempty"`
	OldCustomField134      string    `json:"old_custom_field_134,omitempty"`
	OldCustomField135      string    `json:"old_custom_field_135,omitempty"`
	OldCustomField136      string    `json:"old_custom_field_136,omitempty"`
	OldCustomField137      string    `json:"old_custom_field_137,omitempty"`
	OldCustomField138      string    `json:"old_custom_field_138,omitempty"`
	OldCustomField139      string    `json:"old_custom_field_139,omitempty"`
	OldCustomField140      string    `json:"old_custom_field_140,omitempty"`
	OldCustomField141      string    `json:"old_custom_field_141,omitempty"`
	OldCustomField142      string    `json:"old_custom_field_142,omitempty"`
	OldCustomField143      string    `json:"old_custom_field_143,omitempty"`
	OldCustomField144      string    `json:"old_custom_field_144,omitempty"`
	OldCustomField145      string    `json:"old_custom_field_145,omitempty"`
	OldCustomField146      string    `json:"old_custom_field_146,omitempty"`
	OldCustomField147      string    `json:"old_custom_field_147,omitempty"`
	OldCustomField148      string    `json:"old_custom_field_148,omitempty"`
	OldCustomField149      string    `json:"old_custom_field_149,omitempty"`
	OldCustomField150      string    `json:"old_custom_field_150,omitempty"`
	OldCustomField151      string    `json:"old_custom_field_151,omitempty"`
	OldCustomField152      string    `json:"old_custom_field_152,omitempty"`
	OldCustomField153      string    `json:"old_custom_field_153,omitempty"`
	OldCustomField154      string    `json:"old_custom_field_154,omitempty"`
	OldCustomField155      string    `json:"old_custom_field_155,omitempty"`
	OldCustomField156      string    `json:"old_custom_field_156,omitempty"`
	OldCustomField157      string    `json:"old_custom_field_157,omitempty"`
	OldCustomField158      string    `json:"old_custom_field_158,omitempty"`
	OldCustomField159      string    `json:"old_custom_field_159,omitempty"`
	OldCustomField160      string    `json:"old_custom_field_160,omitempty"`
	OldCustomField161      string    `json:"old_custom_field_161,omitempty"`
	OldCustomField162      string    `json:"old_custom_field_162,omitempty"`
	OldCustomField163      string    `json:"old_custom_field_163,omitempty"`
	OldCustomField164      string    `json:"old_custom_field_164,omitempty"`
	OldCustomField165      string    `json:"old_custom_field_165,omitempty"`
	OldCustomField166      string    `json:"old_custom_field_166,omitempty"`
	OldCustomField167      string    `json:"old_custom_field_167,omitempty"`
	OldCustomField168      string    `json:"old_custom_field_168,omitempty"`
	OldCustomField169      string    `json:"old_custom_field_169,omitempty"`
	OldCustomField170      string    `json:"old_custom_field_170,omitempty"`
	OldCustomField171      string    `json:"old_custom_field_171,omitempty"`
	OldCustomField172      string    `json:"old_custom_field_172,omitempty"`
	OldCustomField173      string    `json:"old_custom_field_173,omitempty"`
	OldCustomField174      string    `json:"old_custom_field_174,omitempty"`
	OldCustomField175      string    `json:"old_custom_field_175,omitempty"`
	OldCustomField176      string    `json:"old_custom_field_176,omitempty"`
	OldCustomField177      string    `json:"old_custom_field_177,omitempty"`
	OldCustomField178      string    `json:"old_custom_field_178,omitempty"`
	OldCustomField179      string    `json:"old_custom_field_179,omitempty"`
	OldCustomField180      string    `json:"old_custom_field_180,omitempty"`
	OldCustomField181      string    `json:"old_custom_field_181,omitempty"`
	OldCustomField182      string    `json:"old_custom_field_182,omitempty"`
	OldCustomField183      string    `json:"old_custom_field_183,omitempty"`
	OldCustomField184      string    `json:"old_custom_field_184,omitempty"`
	OldCustomField185      string    `json:"old_custom_field_185,omitempty"`
	OldCustomField186      string    `json:"old_custom_field_186,omitempty"`
	OldCustomField187      string    `json:"old_custom_field_187,omitempty"`
	OldCustomField188      string    `json:"old_custom_field_188,omitempty"`
	OldCustomField189      string    `json:"old_custom_field_189,omitempty"`
	OldCustomField190      string    `json:"old_custom_field_190,omitempty"`
	OldCustomField191      string    `json:"old_custom_field_191,omitempty"`
	OldCustomField192      string    `json:"old_custom_field_192,omitempty"`
	OldCustomField193      string    `json:"old_custom_field_193,omitempty"`
	OldCustomField194      string    `json:"old_custom_field_194,omitempty"`
	OldCustomField195      string    `json:"old_custom_field_195,omitempty"`
	OldCustomField196      string    `json:"old_custom_field_196,omitempty"`
	OldCustomField197      string    `json:"old_custom_field_197,omitempty"`
	OldCustomField198      string    `json:"old_custom_field_198,omitempty"`
	OldCustomField199      string    `json:"old_custom_field_199,omitempty"`
	OldCustomField200      string    `json:"old_custom_field_200,omitempty"`
	NewID                  string    `json:"new_id,omitempty"`
	NewSecretRootID        string    `json:"new_secret_root_id,omitempty"`
	NewSid                 string    `json:"new_sid,omitempty"`
	NewProjectID           string    `json:"new_project_id,omitempty"`
	NewParentID            string    `json:"new_parent_id,omitempty"`
	NewTitle               string    `json:"new_title,omitempty"`
	NewDescription         string    `json:"new_description,omitempty"`
	NewMarkdownDescription string    `json:"new_markdown_description,omitempty"`
	NewDescriptionType     string    `json:"new_description_type,omitempty"`
	NewModule              string    `json:"new_module,omitempty"`
	NewMilestone           string    `json:"new_milestone,omitempty"`
	NewReporter            string    `json:"new_reporter,omitempty"`
	NewDeadline            string    `json:"new_deadline,omitempty"`
	NewCreated             string    `json:"new_created,omitempty"`
	NewResolved            string    `json:"new_resolved,omitempty"`
	NewClosed              string    `json:"new_closed,omitempty"`
	NewModified            string    `json:"new_modified,omitempty"`
	NewLastModify          string    `json:"new_lastmodify,omitempty"`
	NewAuditer             string    `json:"new_auditer,omitempty"`
	NewDe                  string    `json:"new_de,omitempty"`
	NewTe                  string    `json:"new_te,omitempty"`
	NewConfirmer           string    `json:"new_confirmer,omitempty"`
	NewCurrentOwner        string    `json:"new_current_owner,omitempty"`
	NewParticipator        string    `json:"new_participator,omitempty"`
	NewCloser              string    `json:"new_closer,omitempty"`
	NewStatus              string    `json:"new_status,omitempty"`
	NewResolution          string    `json:"new_resolution,omitempty"`
	NewPriority            string    `json:"new_priority,omitempty"`
	NewSeverity            string    `json:"new_severity,omitempty"`
	NewPlatform            string    `json:"new_platform,omitempty"`
	NewOs                  string    `json:"new_os,omitempty"`
	NewTestMode            string    `json:"new_testmode,omitempty"`
	NewTestType            string    `json:"new_testtype,omitempty"`
	NewTestPhase           string    `json:"new_testphase,omitempty"`
	NewSource              string    `json:"new_source,omitempty"`
	NewFrequency           string    `json:"new_frequency,omitempty"`
	NewCc                  string    `json:"new_cc,omitempty"`
	NewEstimate            string    `json:"new_estimate,omitempty"`
	NewFlows               string    `json:"new_flows,omitempty"`
	NewVersionReport       string    `json:"new_version_report,omitempty"`
	NewVersionTest         string    `json:"new_version_test,omitempty"`
	NewVersionFix          string    `json:"new_version_fix,omitempty"`
	NewVersionClose        string    `json:"new_version_close,omitempty"`
	NewDelayed             string    `json:"new_delayed,omitempty"`
	NewCustomFieldOne      string    `json:"new_custom_field_one,omitempty"`
	NewCustomFieldTwo      string    `json:"new_custom_field_two,omitempty"`
	NewCustomFieldThree    string    `json:"new_custom_field_three,omitempty"`
	NewCustomFieldFour     string    `json:"new_custom_field_four,omitempty"`
	NewCustomFieldFive     string    `json:"new_custom_field_five,omitempty"`
	NewRegressionNumber    string    `json:"new_regression_number,omitempty"`
	NewIssueID             string    `json:"new_issue_id,omitempty"`
	NewSupportID           string    `json:"new_support_id,omitempty"`
	NewSupportForumID      string    `json:"new_support_forum_id,omitempty"`
	NewCreatedFrom         string    `json:"new_created_from,omitempty"`
	NewBaselineFind        string    `json:"new_baseline_find,omitempty"`
	NewBaselineJoin        string    `json:"new_baseline_join,omitempty"`
	NewBaselineClose       string    `json:"new_baseline_close,omitempty"`
	NewTicketID            string    `json:"new_ticket_id,omitempty"`
	NewStoryID             string    `json:"new_story_id,omitempty"`
	NewBaselineTest        string    `json:"new_baseline_test,omitempty"`
	NewOriginPhase         string    `json:"new_originphase,omitempty"`
	NewSourcePhase         string    `json:"new_sourcephase,omitempty"`
	NewBugType             string    `json:"new_bugtype,omitempty"`
	NewFeature             string    `json:"new_feature,omitempty"`
	NewInProgressTime      string    `json:"new_in_progress_time,omitempty"`
	NewVerifyTime          string    `json:"new_verify_time,omitempty"`
	NewRejectTime          string    `json:"new_reject_time,omitempty"`
	NewReopenTime          string    `json:"new_reopen_time,omitempty"`
	NewAuditTime           string    `json:"new_audit_time,omitempty"`
	NewSuspendTime         string    `json:"new_suspend_time,omitempty"`
	NewAssignedTime        string    `json:"new_assigned_time,omitempty"`
	NewIterationID         string    `json:"new_iteration_id,omitempty"`
	NewCustomField6        string    `json:"new_custom_field_6,omitempty"`
	NewCustomField7        string    `json:"new_custom_field_7,omitempty"`
	NewCustomField8        string    `json:"new_custom_field_8,omitempty"`
	NewCustomField9        string    `json:"new_custom_field_9,omitempty"`
	NewCustomField10       string    `json:"new_custom_field_10,omitempty"`
	NewCustomField11       string    `json:"new_custom_field_11,omitempty"`
	NewCustomField12       string    `json:"new_custom_field_12,omitempty"`
	NewCustomField13       string    `json:"new_custom_field_13,omitempty"`
	NewCustomField14       string    `json:"new_custom_field_14,omitempty"`
	NewCustomField15       string    `json:"new_custom_field_15,omitempty"`
	NewCustomField16       string    `json:"new_custom_field_16,omitempty"`
	NewCustomField17       string    `json:"new_custom_field_17,omitempty"`
	NewCustomField18       string    `json:"new_custom_field_18,omitempty"`
	NewCustomField19       string    `json:"new_custom_field_19,omitempty"`
	NewCustomField20       string    `json:"new_custom_field_20,omitempty"`
	NewCustomField21       string    `json:"new_custom_field_21,omitempty"`
	NewCustomField22       string    `json:"new_custom_field_22,omitempty"`
	NewCustomField23       string    `json:"new_custom_field_23,omitempty"`
	NewCustomField24       string    `json:"new_custom_field_24,omitempty"`
	NewCustomField25       string    `json:"new_custom_field_25,omitempty"`
	NewCustomField26       string    `json:"new_custom_field_26,omitempty"`
	NewCustomField27       string    `json:"new_custom_field_27,omitempty"`
	NewCustomField28       string    `json:"new_custom_field_28,omitempty"`
	NewCustomField29       string    `json:"new_custom_field_29,omitempty"`
	NewCustomField30       string    `json:"new_custom_field_30,omitempty"`
	NewCustomField31       string    `json:"new_custom_field_31,omitempty"`
	NewCustomField32       string    `json:"new_custom_field_32,omitempty"`
	NewCustomField33       string    `json:"new_custom_field_33,omitempty"`
	NewCustomField34       string    `json:"new_custom_field_34,omitempty"`
	NewCustomField35       string    `json:"new_custom_field_35,omitempty"`
	NewCustomField36       string    `json:"new_custom_field_36,omitempty"`
	NewCustomField37       string    `json:"new_custom_field_37,omitempty"`
	NewCustomField38       string    `json:"new_custom_field_38,omitempty"`
	NewCustomField39       string    `json:"new_custom_field_39,omitempty"`
	NewCustomField40       string    `json:"new_custom_field_40,omitempty"`
	NewCustomField41       string    `json:"new_custom_field_41,omitempty"`
	NewCustomField42       string    `json:"new_custom_field_42,omitempty"`
	NewCustomField43       string    `json:"new_custom_field_43,omitempty"`
	NewCustomField44       string    `json:"new_custom_field_44,omitempty"`
	NewCustomField45       string    `json:"new_custom_field_45,omitempty"`
	NewCustomField46       string    `json:"new_custom_field_46,omitempty"`
	NewCustomField47       string    `json:"new_custom_field_47,omitempty"`
	NewCustomField48       string    `json:"new_custom_field_48,omitempty"`
	NewCustomField49       string    `json:"new_custom_field_49,omitempty"`
	NewCustomField50       string    `json:"new_custom_field_50,omitempty"`
	NewCustomField51       string    `json:"new_custom_field_51,omitempty"`
	NewCustomField52       string    `json:"new_custom_field_52,omitempty"`
	NewCustomField53       string    `json:"new_custom_field_53,omitempty"`
	NewCustomField54       string    `json:"new_custom_field_54,omitempty"`
	NewCustomField55       string    `json:"new_custom_field_55,omitempty"`
	NewCustomField56       string    `json:"new_custom_field_56,omitempty"`
	NewCustomField57       string    `json:"new_custom_field_57,omitempty"`
	NewCustomField58       string    `json:"new_custom_field_58,omitempty"`
	NewCustomField59       string    `json:"new_custom_field_59,omitempty"`
	NewCustomField60       string    `json:"new_custom_field_60,omitempty"`
	NewCustomField61       string    `json:"new_custom_field_61,omitempty"`
	NewCustomField62       string    `json:"new_custom_field_62,omitempty"`
	NewCustomField63       string    `json:"new_custom_field_63,omitempty"`
	NewCustomField64       string    `json:"new_custom_field_64,omitempty"`
	NewCustomField65       string    `json:"new_custom_field_65,omitempty"`
	NewCustomField66       string    `json:"new_custom_field_66,omitempty"`
	NewCustomField67       string    `json:"new_custom_field_67,omitempty"`
	NewCustomField68       string    `json:"new_custom_field_68,omitempty"`
	NewCustomField69       string    `json:"new_custom_field_69,omitempty"`
	NewCustomField70       string    `json:"new_custom_field_70,omitempty"`
	NewCustomField71       string    `json:"new_custom_field_71,omitempty"`
	NewCustomField72       string    `json:"new_custom_field_72,omitempty"`
	NewCustomField73       string    `json:"new_custom_field_73,omitempty"`
	NewCustomField74       string    `json:"new_custom_field_74,omitempty"`
	NewCustomField75       string    `json:"new_custom_field_75,omitempty"`
	NewCustomField76       string    `json:"new_custom_field_76,omitempty"`
	NewCustomField77       string    `json:"new_custom_field_77,omitempty"`
	NewCustomField78       string    `json:"new_custom_field_78,omitempty"`
	NewCustomField79       string    `json:"new_custom_field_79,omitempty"`
	NewCustomField80       string    `json:"new_custom_field_80,omitempty"`
	NewCustomField81       string    `json:"new_custom_field_81,omitempty"`
	NewCustomField82       string    `json:"new_custom_field_82,omitempty"`
	NewCustomField83       string    `json:"new_custom_field_83,omitempty"`
	NewCustomField84       string    `json:"new_custom_field_84,omitempty"`
	NewCustomField85       string    `json:"new_custom_field_85,omitempty"`
	NewCustomField86       string    `json:"new_custom_field_86,omitempty"`
	NewCustomField87       string    `json:"new_custom_field_87,omitempty"`
	NewCustomField88       string    `json:"new_custom_field_88,omitempty"`
	NewCustomField89       string    `json:"new_custom_field_89,omitempty"`
	NewCustomField90       string    `json:"new_custom_field_90,omitempty"`
	NewCustomField91       string    `json:"new_custom_field_91,omitempty"`
	NewCustomField92       string    `json:"new_custom_field_92,omitempty"`
	NewCustomField93       string    `json:"new_custom_field_93,omitempty"`
	NewCustomField94       string    `json:"new_custom_field_94,omitempty"`
	NewCustomField95       string    `json:"new_custom_field_95,omitempty"`
	NewCustomField96       string    `json:"new_custom_field_96,omitempty"`
	NewCustomField97       string    `json:"new_custom_field_97,omitempty"`
	NewCustomField98       string    `json:"new_custom_field_98,omitempty"`
	NewCustomField99       string    `json:"new_custom_field_99,omitempty"`
	NewCustomField100      string    `json:"new_custom_field_100,omitempty"`
	NewCustomPlanField1    string    `json:"new_custom_plan_field_1,omitempty"`
	NewCustomPlanField2    string    `json:"new_custom_plan_field_2,omitempty"`
	NewCustomPlanField3    string    `json:"new_custom_plan_field_3,omitempty"`
	NewCustomPlanField4    string    `json:"new_custom_plan_field_4,omitempty"`
	NewCustomPlanField5    string    `json:"new_custom_plan_field_5,omitempty"`
	NewCustomPlanField6    string    `json:"new_custom_plan_field_6,omitempty"`
	NewCustomPlanField7    string    `json:"new_custom_plan_field_7,omitempty"`
	NewCustomPlanField8    string    `json:"new_custom_plan_field_8,omitempty"`
	NewCustomPlanField9    string    `json:"new_custom_plan_field_9,omitempty"`
	NewCustomPlanField10   string    `json:"new_custom_plan_field_10,omitempty"`
	NewTemplateID          string    `json:"new_template_id,omitempty"`
	NewBegin               string    `json:"new_begin,omitempty"`
	NewDue                 string    `json:"new_due,omitempty"`
	NewReleaseID           string    `json:"new_release_id,omitempty"`
	NewFixer               string    `json:"new_fixer,omitempty"`
	NewFollower            string    `json:"new_follower,omitempty"`
	NewSyncType            string    `json:"new_sync_type,omitempty"`
	NewLabel               string    `json:"new_label,omitempty"`
	NewEffort              string    `json:"new_effort,omitempty"`
	NewEffortCompleted     string    `json:"new_effort_completed,omitempty"`
	NewExceed              string    `json:"new_exceed,omitempty"`
	NewRemain              string    `json:"new_remain,omitempty"`
	NewProgress            string    `json:"new_progress,omitempty"`
	NewSize                string    `json:"new_size,omitempty"`
	NewCustomField101      string    `json:"new_custom_field_101,omitempty"`
	NewCustomField102      string    `json:"new_custom_field_102,omitempty"`
	NewCustomField103      string    `json:"new_custom_field_103,omitempty"`
	NewCustomField104      string    `json:"new_custom_field_104,omitempty"`
	NewCustomField105      string    `json:"new_custom_field_105,omitempty"`
	NewCustomField106      string    `json:"new_custom_field_106,omitempty"`
	NewCustomField107      string    `json:"new_custom_field_107,omitempty"`
	NewCustomField108      string    `json:"new_custom_field_108,omitempty"`
	NewCustomField109      string    `json:"new_custom_field_109,omitempty"`
	NewCustomField110      string    `json:"new_custom_field_110,omitempty"`
	NewCustomField111      string    `json:"new_custom_field_111,omitempty"`
	NewCustomField112      string    `json:"new_custom_field_112,omitempty"`
	NewCustomField113      string    `json:"new_custom_field_113,omitempty"`
	NewCustomField114      string    `json:"new_custom_field_114,omitempty"`
	NewCustomField115      string    `json:"new_custom_field_115,omitempty"`
	NewCustomField116      string    `json:"new_custom_field_116,omitempty"`
	NewCustomField117      string    `json:"new_custom_field_117,omitempty"`
	NewCustomField118      string    `json:"new_custom_field_118,omitempty"`
	NewCustomField119      string    `json:"new_custom_field_119,omitempty"`
	NewCustomField120      string    `json:"new_custom_field_120,omitempty"`
	NewCustomField121      string    `json:"new_custom_field_121,omitempty"`
	NewCustomField122      string    `json:"new_custom_field_122,omitempty"`
	NewCustomField123      string    `json:"new_custom_field_123,omitempty"`
	NewCustomField124      string    `json:"new_custom_field_124,omitempty"`
	NewCustomField125      string    `json:"new_custom_field_125,omitempty"`
	NewCustomField126      string    `json:"new_custom_field_126,omitempty"`
	NewCustomField127      string    `json:"new_custom_field_127,omitempty"`
	NewCustomField128      string    `json:"new_custom_field_128,omitempty"`
	NewCustomField129      string    `json:"new_custom_field_129,omitempty"`
	NewCustomField130      string    `json:"new_custom_field_130,omitempty"`
	NewCustomField131      string    `json:"new_custom_field_131,omitempty"`
	NewCustomField132      string    `json:"new_custom_field_132,omitempty"`
	NewCustomField133      string    `json:"new_custom_field_133,omitempty"`
	NewCustomField134      string    `json:"new_custom_field_134,omitempty"`
	NewCustomField135      string    `json:"new_custom_field_135,omitempty"`
	NewCustomField136      string    `json:"new_custom_field_136,omitempty"`
	NewCustomField137      string    `json:"new_custom_field_137,omitempty"`
	NewCustomField138      string    `json:"new_custom_field_138,omitempty"`
	NewCustomField139      string    `json:"new_custom_field_139,omitempty"`
	NewCustomField140      string    `json:"new_custom_field_140,omitempty"`
	NewCustomField141      string    `json:"new_custom_field_141,omitempty"`
	NewCustomField142      string    `json:"new_custom_field_142,omitempty"`
	NewCustomField143      string    `json:"new_custom_field_143,omitempty"`
	NewCustomField144      string    `json:"new_custom_field_144,omitempty"`
	NewCustomField145      string    `json:"new_custom_field_145,omitempty"`
	NewCustomField146      string    `json:"new_custom_field_146,omitempty"`
	NewCustomField147      string    `json:"new_custom_field_147,omitempty"`
	NewCustomField148      string    `json:"new_custom_field_148,omitempty"`
	NewCustomField149      string    `json:"new_custom_field_149,omitempty"`
	NewCustomField150      string    `json:"new_custom_field_150,omitempty"`
	NewCustomField151      string    `json:"new_custom_field_151,omitempty"`
	NewCustomField152      string    `json:"new_custom_field_152,omitempty"`
	NewCustomField153      string    `json:"new_custom_field_153,omitempty"`
	NewCustomField154      string    `json:"new_custom_field_154,omitempty"`
	NewCustomField155      string    `json:"new_custom_field_155,omitempty"`
	NewCustomField156      string    `json:"new_custom_field_156,omitempty"`
	NewCustomField157      string    `json:"new_custom_field_157,omitempty"`
	NewCustomField158      string    `json:"new_custom_field_158,omitempty"`
	NewCustomField159      string    `json:"new_custom_field_159,omitempty"`
	NewCustomField160      string    `json:"new_custom_field_160,omitempty"`
	NewCustomField161      string    `json:"new_custom_field_161,omitempty"`
	NewCustomField162      string    `json:"new_custom_field_162,omitempty"`
	NewCustomField163      string    `json:"new_custom_field_163,omitempty"`
	NewCustomField164      string    `json:"new_custom_field_164,omitempty"`
	NewCustomField165      string    `json:"new_custom_field_165,omitempty"`
	NewCustomField166      string    `json:"new_custom_field_166,omitempty"`
	NewCustomField167      string    `json:"new_custom_field_167,omitempty"`
	NewCustomField168      string    `json:"new_custom_field_168,omitempty"`
	NewCustomField169      string    `json:"new_custom_field_169,omitempty"`
	NewCustomField170      string    `json:"new_custom_field_170,omitempty"`
	NewCustomField171      string    `json:"new_custom_field_171,omitempty"`
	NewCustomField172      string    `json:"new_custom_field_172,omitempty"`
	NewCustomField173      string    `json:"new_custom_field_173,omitempty"`
	NewCustomField174      string    `json:"new_custom_field_174,omitempty"`
	NewCustomField175      string    `json:"new_custom_field_175,omitempty"`
	NewCustomField176      string    `json:"new_custom_field_176,omitempty"`
	NewCustomField177      string    `json:"new_custom_field_177,omitempty"`
	NewCustomField178      string    `json:"new_custom_field_178,omitempty"`
	NewCustomField179      string    `json:"new_custom_field_179,omitempty"`
	NewCustomField180      string    `json:"new_custom_field_180,omitempty"`
	NewCustomField181      string    `json:"new_custom_field_181,omitempty"`
	NewCustomField182      string    `json:"new_custom_field_182,omitempty"`
	NewCustomField183      string    `json:"new_custom_field_183,omitempty"`
	NewCustomField184      string    `json:"new_custom_field_184,omitempty"`
	NewCustomField185      string    `json:"new_custom_field_185,omitempty"`
	NewCustomField186      string    `json:"new_custom_field_186,omitempty"`
	NewCustomField187      string    `json:"new_custom_field_187,omitempty"`
	NewCustomField188      string    `json:"new_custom_field_188,omitempty"`
	NewCustomField189      string    `json:"new_custom_field_189,omitempty"`
	NewCustomField190      string    `json:"new_custom_field_190,omitempty"`
	NewCustomField191      string    `json:"new_custom_field_191,omitempty"`
	NewCustomField192      string    `json:"new_custom_field_192,omitempty"`
	NewCustomField193      string    `json:"new_custom_field_193,omitempty"`
	NewCustomField194      string    `json:"new_custom_field_194,omitempty"`
	NewCustomField195      string    `json:"new_custom_field_195,omitempty"`
	NewCustomField196      string    `json:"new_custom_field_196,omitempty"`
	NewCustomField197      string    `json:"new_custom_field_197,omitempty"`
	NewCustomField198      string    `json:"new_custom_field_198,omitempty"`
	NewCustomField199      string    `json:"new_custom_field_199,omitempty"`
	NewCustomField200      string    `json:"new_custom_field_200,omitempty"`
	ChangeFields           string    `json:"change_fields,omitempty"`
	Secret                 string    `json:"secret,omitempty"`
	RioToken               string    `json:"rio_token,omitempty"`
	DevProxyHost           string    `json:"devproxy_host,omitempty"`
	QueueID                string    `json:"queue_id,omitempty"`
	EventID                string    `json:"event_id,omitempty"`
	Created                string    `json:"created,omitempty"`
}

type BugDeleteEvent struct {
	Event          EventType `json:"event,omitempty"`
	EventFrom      string    `json:"event_from,omitempty"`
	Referer        string    `json:"referer,omitempty"`
	WorkspaceID    string    `json:"workspace_id,omitempty"`
	CurrentUser    string    `json:"current_user,omitempty"`
	ID             string    `json:"id,omitempty"`
	OpType         string    `json:"op_type,omitempty"`
	OldIterationID string    `json:"old_iteration_id,omitempty"`
	Secret         string    `json:"secret,omitempty"`
	RioToken       string    `json:"rio_token,omitempty"`
	DevProxyHost   string    `json:"devproxy_host,omitempty"`
	QueueID        string    `json:"queue_id,omitempty"`
	EventID        string    `json:"event_id,omitempty"`
	Created        string    `json:"created,omitempty"`
}
