package webhook

type TaskCreateEvent struct {
	Event               EventType `json:"event,omitempty"`
	EventFrom           string    `json:"event_from,omitempty"`
	Referer             string    `json:"referer,omitempty"`
	WorkspaceID         string    `json:"workspace_id,omitempty"`
	CurrentUser         string    `json:"current_user,omitempty"`
	ID                  string    `json:"id,omitempty"`
	Name                string    `json:"name,omitempty"`
	Status              string    `json:"status,omitempty"`
	StoryID             string    `json:"story_id,omitempty"`
	IterationID         string    `json:"iteration_id,omitempty"`
	Creator             string    `json:"creator,omitempty"`
	Created             string    `json:"created,omitempty"`
	Description         string    `json:"description,omitempty"`
	MarkdownDescription string    `json:"markdown_description,omitempty"`
	DescriptionType     string    `json:"description_type,omitempty"`
	Effort              string    `json:"effort,omitempty"`
	ReleaseID           string    `json:"release_id,omitempty"`
	Owner               string    `json:"owner,omitempty"`
	EntityType          string    `json:"entity_type,omitempty"`
	CustomPlanField1    string    `json:"custom_plan_field_1,omitempty"`
	CustomPlanField2    string    `json:"custom_plan_field_2,omitempty"`
	CustomPlanField3    string    `json:"custom_plan_field_3,omitempty"`
	CustomPlanField4    string    `json:"custom_plan_field_4,omitempty"`
	CustomPlanField5    string    `json:"custom_plan_field_5,omitempty"`
	CustomPlanField6    string    `json:"custom_plan_field_6,omitempty"`
	CustomPlanField7    string    `json:"custom_plan_field_7,omitempty"`
	CustomPlanField8    string    `json:"custom_plan_field_8,omitempty"`
	CustomPlanField9    string    `json:"custom_plan_field_9,omitempty"`
	CustomPlanField10   string    `json:"custom_plan_field_10,omitempty"`
	ParentID            string    `json:"parent_id,omitempty"`
	AncestorID          string    `json:"ancestor_id,omitempty"`
	ChildrenID          string    `json:"children_id,omitempty"`
	Secret              string    `json:"secret,omitempty"`
	RioToken            string    `json:"rio_token,omitempty"`
	DevProxyHost        string    `json:"devproxy_host,omitempty"`
	QueueID             string    `json:"queue_id,omitempty"`
	EventID             string    `json:"event_id,omitempty"`
}

type TaskUpdateEvent struct {
	Event                  EventType `json:"event,omitempty"`
	EventFrom              string    `json:"event_from,omitempty"`
	Referer                string    `json:"referer,omitempty"`
	WorkspaceID            string    `json:"workspace_id,omitempty"`
	CurrentUser            string    `json:"current_user,omitempty"`
	ID                     string    `json:"id,omitempty"`
	OldID                  string    `json:"old_id,omitempty"`
	OldName                string    `json:"old_name,omitempty"`
	OldDescription         string    `json:"old_description,omitempty"`
	OldMarkdownDescription string    `json:"old_markdown_description,omitempty"`
	OldDescriptionType     string    `json:"old_description_type,omitempty"`
	OldCreator             string    `json:"old_creator,omitempty"`
	OldCreated             string    `json:"old_created,omitempty"`
	OldModified            string    `json:"old_modified,omitempty"`
	OldParentID            string    `json:"old_parent_id,omitempty"`
	OldChildrenID          string    `json:"old_children_id,omitempty"`
	OldAncestorID          string    `json:"old_ancestor_id,omitempty"`
	OldPath                string    `json:"old_path,omitempty"`
	OldLevel               string    `json:"old_level,omitempty"`
	OldWorkspaceID         string    `json:"old_workspace_id,omitempty"`
	OldStatus              string    `json:"old_status,omitempty"`
	OldFlows               string    `json:"old_flows,omitempty"`
	OldPriority            string    `json:"old_priority,omitempty"`
	OldOwner               string    `json:"old_owner,omitempty"`
	OldCc                  string    `json:"old_cc,omitempty"`
	OldBegin               string    `json:"old_begin,omitempty"`
	OldDue                 string    `json:"old_due,omitempty"`
	OldSource              string    `json:"old_source,omitempty"`
	OldWorkitemID          string    `json:"old_workitem_id,omitempty"`
	OldStoryID             string    `json:"old_story_id,omitempty"`
	OldIterationID         string    `json:"old_iteration_id,omitempty"`
	OldSubstrace           string    `json:"old_substrace,omitempty"`
	OldCompleted           string    `json:"old_completed,omitempty"`
	OldEffort              string    `json:"old_effort,omitempty"`
	OldEffortCompleted     string    `json:"old_effort_completed,omitempty"`
	OldEffortTotal         string    `json:"old_effort_total,omitempty"`
	OldExceed              string    `json:"old_exceed,omitempty"`
	OldRemain              string    `json:"old_remain,omitempty"`
	OldProgress            string    `json:"old_progress,omitempty"`
	OldEntityType          string    `json:"old_entity_type,omitempty"`
	OldCustomFieldOne      string    `json:"old_custom_field_one,omitempty"`
	OldCustomFieldTwo      string    `json:"old_custom_field_two,omitempty"`
	OldCustomFieldThree    string    `json:"old_custom_field_three,omitempty"`
	OldCustomFieldFour     string    `json:"old_custom_field_four,omitempty"`
	OldCustomFieldFive     string    `json:"old_custom_field_five,omitempty"`
	OldCustomFieldSix      string    `json:"old_custom_field_six,omitempty"`
	OldCustomFieldSeven    string    `json:"old_custom_field_seven,omitempty"`
	OldCustomFieldEight    string    `json:"old_custom_field_eight,omitempty"`
	OldCustomField9        string    `json:"old_custom_field_9,omitempty"`
	OldCustomField10       string    `json:"old_custom_field_10,omitempty"`
	OldCustomField11       string    `json:"old_custom_field_11,omitempty"`
	OldCustomField12       string    `json:"old_custom_field_12,omitempty"`
	OldCustomField13       string    `json:"old_custom_field_13,omitempty"`
	OldCustomField14       string    `json:"old_custom_field_14,omitempty"`
	OldCustomField15       string    `json:"old_custom_field_15,omitempty"`
	OldCustomField16       string    `json:"old_custom_field_16,omitempty"`
	OldCustomField17       string    `json:"old_custom_field_17,omitempty"`
	OldCustomField18       string    `json:"old_custom_field_18,omitempty"`
	OldCustomField19       string    `json:"old_custom_field_19,omitempty"`
	OldCustomField20       string    `json:"old_custom_field_20,omitempty"`
	OldCustomField21       string    `json:"old_custom_field_21,omitempty"`
	OldCustomField22       string    `json:"old_custom_field_22,omitempty"`
	OldCustomField23       string    `json:"old_custom_field_23,omitempty"`
	OldCustomField24       string    `json:"old_custom_field_24,omitempty"`
	OldCustomField25       string    `json:"old_custom_field_25,omitempty"`
	OldCustomField26       string    `json:"old_custom_field_26,omitempty"`
	OldCustomField27       string    `json:"old_custom_field_27,omitempty"`
	OldCustomField28       string    `json:"old_custom_field_28,omitempty"`
	OldCustomField29       string    `json:"old_custom_field_29,omitempty"`
	OldCustomField30       string    `json:"old_custom_field_30,omitempty"`
	OldCustomField31       string    `json:"old_custom_field_31,omitempty"`
	OldCustomField32       string    `json:"old_custom_field_32,omitempty"`
	OldCustomField33       string    `json:"old_custom_field_33,omitempty"`
	OldCustomField34       string    `json:"old_custom_field_34,omitempty"`
	OldCustomField35       string    `json:"old_custom_field_35,omitempty"`
	OldCustomField36       string    `json:"old_custom_field_36,omitempty"`
	OldCustomField37       string    `json:"old_custom_field_37,omitempty"`
	OldCustomField38       string    `json:"old_custom_field_38,omitempty"`
	OldCustomField39       string    `json:"old_custom_field_39,omitempty"`
	OldCustomField40       string    `json:"old_custom_field_40,omitempty"`
	OldCustomField41       string    `json:"old_custom_field_41,omitempty"`
	OldCustomField42       string    `json:"old_custom_field_42,omitempty"`
	OldCustomField43       string    `json:"old_custom_field_43,omitempty"`
	OldCustomField44       string    `json:"old_custom_field_44,omitempty"`
	OldCustomField45       string    `json:"old_custom_field_45,omitempty"`
	OldCustomField46       string    `json:"old_custom_field_46,omitempty"`
	OldCustomField47       string    `json:"old_custom_field_47,omitempty"`
	OldCustomField48       string    `json:"old_custom_field_48,omitempty"`
	OldCustomField49       string    `json:"old_custom_field_49,omitempty"`
	OldCustomField50       string    `json:"old_custom_field_50,omitempty"`
	OldCustomPlanField1    string    `json:"old_custom_plan_field_1,omitempty"`
	OldCustomPlanField2    string    `json:"old_custom_plan_field_2,omitempty"`
	OldCustomPlanField3    string    `json:"old_custom_plan_field_3,omitempty"`
	OldCustomPlanField4    string    `json:"old_custom_plan_field_4,omitempty"`
	OldCustomPlanField5    string    `json:"old_custom_plan_field_5,omitempty"`
	OldCustomPlanField6    string    `json:"old_custom_plan_field_6,omitempty"`
	OldCustomPlanField7    string    `json:"old_custom_plan_field_7,omitempty"`
	OldCustomPlanField8    string    `json:"old_custom_plan_field_8,omitempty"`
	OldCustomPlanField9    string    `json:"old_custom_plan_field_9,omitempty"`
	OldCustomPlanField10   string    `json:"old_custom_plan_field_10,omitempty"`
	OldAttachmentCount     string    `json:"old_attachment_count,omitempty"`
	OldHasAttachment       string    `json:"old_has_attachment,omitempty"`
	OldFollower            string    `json:"old_follower,omitempty"`
	OldCreatedFrom         string    `json:"old_created_from,omitempty"`
	OldPredecessorCount    string    `json:"old_predecessor_count,omitempty"`
	OldSuccessorCount      string    `json:"old_successor_count,omitempty"`
	OldReleaseID           string    `json:"old_release_id,omitempty"`
	OldLabel               string    `json:"old_label,omitempty"`
	OldNewStoryID          string    `json:"old_new_story_id,omitempty"`
	NewID                  string    `json:"new_id,omitempty"`
	NewName                string    `json:"new_name,omitempty"`
	NewDescription         string    `json:"new_description,omitempty"`
	NewMarkdownDescription string    `json:"new_markdown_description,omitempty"`
	NewDescriptionType     string    `json:"new_description_type,omitempty"`
	NewCreator             string    `json:"new_creator,omitempty"`
	NewCreated             string    `json:"new_created,omitempty"`
	NewModified            string    `json:"new_modified,omitempty"`
	NewParentID            string    `json:"new_parent_id,omitempty"`
	NewChildrenID          string    `json:"new_children_id,omitempty"`
	NewAncestorID          string    `json:"new_ancestor_id,omitempty"`
	NewPath                string    `json:"new_path,omitempty"`
	NewLevel               string    `json:"new_level,omitempty"`
	NewWorkspaceID         string    `json:"new_workspace_id,omitempty"`
	NewStatus              string    `json:"new_status,omitempty"`
	NewFlows               string    `json:"new_flows,omitempty"`
	NewPriority            string    `json:"new_priority,omitempty"`
	NewOwner               string    `json:"new_owner,omitempty"`
	NewCc                  string    `json:"new_cc,omitempty"`
	NewBegin               string    `json:"new_begin,omitempty"`
	NewDue                 string    `json:"new_due,omitempty"`
	NewSource              string    `json:"new_source,omitempty"`
	NewWorkitemID          string    `json:"new_workitem_id,omitempty"`
	NewStoryID             string    `json:"new_story_id,omitempty"`
	NewIterationID         string    `json:"new_iteration_id,omitempty"`
	NewSubstrace           string    `json:"new_substrace,omitempty"`
	NewCompleted           string    `json:"new_completed,omitempty"`
	NewEffort              string    `json:"new_effort,omitempty"`
	NewEffortCompleted     string    `json:"new_effort_completed,omitempty"`
	NewEffortTotal         string    `json:"new_effort_total,omitempty"`
	NewExceed              string    `json:"new_exceed,omitempty"`
	NewRemain              string    `json:"new_remain,omitempty"`
	NewProgress            string    `json:"new_progress,omitempty"`
	NewEntityType          string    `json:"new_entity_type,omitempty"`
	NewCustomFieldOne      string    `json:"new_custom_field_one,omitempty"`
	NewCustomFieldTwo      string    `json:"new_custom_field_two,omitempty"`
	NewCustomFieldThree    string    `json:"new_custom_field_three,omitempty"`
	NewCustomFieldFour     string    `json:"new_custom_field_four,omitempty"`
	NewCustomFieldFive     string    `json:"new_custom_field_five,omitempty"`
	NewCustomFieldSix      string    `json:"new_custom_field_six,omitempty"`
	NewCustomFieldSeven    string    `json:"new_custom_field_seven,omitempty"`
	NewCustomFieldEight    string    `json:"new_custom_field_eight,omitempty"`
	NewCustomField9        string    `json:"new_custom_field_9,omitempty"`
	NewCustomField10       string    `json:"new_custom_field_10,omitempty"`
	NewCustomField11       string    `json:"new_custom_field_11,omitempty"`
	NewCustomField12       string    `json:"new_custom_field_12,omitempty"`
	NewCustomField13       string    `json:"new_custom_field_13,omitempty"`
	NewCustomField14       string    `json:"new_custom_field_14,omitempty"`
	NewCustomField15       string    `json:"new_custom_field_15,omitempty"`
	NewCustomField16       string    `json:"new_custom_field_16,omitempty"`
	NewCustomField17       string    `json:"new_custom_field_17,omitempty"`
	NewCustomField18       string    `json:"new_custom_field_18,omitempty"`
	NewCustomField19       string    `json:"new_custom_field_19,omitempty"`
	NewCustomField20       string    `json:"new_custom_field_20,omitempty"`
	NewCustomField21       string    `json:"new_custom_field_21,omitempty"`
	NewCustomField22       string    `json:"new_custom_field_22,omitempty"`
	NewCustomField23       string    `json:"new_custom_field_23,omitempty"`
	NewCustomField24       string    `json:"new_custom_field_24,omitempty"`
	NewCustomField25       string    `json:"new_custom_field_25,omitempty"`
	NewCustomField26       string    `json:"new_custom_field_26,omitempty"`
	NewCustomField27       string    `json:"new_custom_field_27,omitempty"`
	NewCustomField28       string    `json:"new_custom_field_28,omitempty"`
	NewCustomField29       string    `json:"new_custom_field_29,omitempty"`
	NewCustomField30       string    `json:"new_custom_field_30,omitempty"`
	NewCustomField31       string    `json:"new_custom_field_31,omitempty"`
	NewCustomField32       string    `json:"new_custom_field_32,omitempty"`
	NewCustomField33       string    `json:"new_custom_field_33,omitempty"`
	NewCustomField34       string    `json:"new_custom_field_34,omitempty"`
	NewCustomField35       string    `json:"new_custom_field_35,omitempty"`
	NewCustomField36       string    `json:"new_custom_field_36,omitempty"`
	NewCustomField37       string    `json:"new_custom_field_37,omitempty"`
	NewCustomField38       string    `json:"new_custom_field_38,omitempty"`
	NewCustomField39       string    `json:"new_custom_field_39,omitempty"`
	NewCustomField40       string    `json:"new_custom_field_40,omitempty"`
	NewCustomField41       string    `json:"new_custom_field_41,omitempty"`
	NewCustomField42       string    `json:"new_custom_field_42,omitempty"`
	NewCustomField43       string    `json:"new_custom_field_43,omitempty"`
	NewCustomField44       string    `json:"new_custom_field_44,omitempty"`
	NewCustomField45       string    `json:"new_custom_field_45,omitempty"`
	NewCustomField46       string    `json:"new_custom_field_46,omitempty"`
	NewCustomField47       string    `json:"new_custom_field_47,omitempty"`
	NewCustomField48       string    `json:"new_custom_field_48,omitempty"`
	NewCustomField49       string    `json:"new_custom_field_49,omitempty"`
	NewCustomField50       string    `json:"new_custom_field_50,omitempty"`
	NewCustomPlanField1    string    `json:"new_custom_plan_field_1,omitempty"`
	NewCustomPlanField2    string    `json:"new_custom_plan_field_2,omitempty"`
	NewCustomPlanField3    string    `json:"new_custom_plan_field_3,omitempty"`
	NewCustomPlanField4    string    `json:"new_custom_plan_field_4,omitempty"`
	NewCustomPlanField5    string    `json:"new_custom_plan_field_5,omitempty"`
	NewCustomPlanField6    string    `json:"new_custom_plan_field_6,omitempty"`
	NewCustomPlanField7    string    `json:"new_custom_plan_field_7,omitempty"`
	NewCustomPlanField8    string    `json:"new_custom_plan_field_8,omitempty"`
	NewCustomPlanField9    string    `json:"new_custom_plan_field_9,omitempty"`
	NewCustomPlanField10   string    `json:"new_custom_plan_field_10,omitempty"`
	NewAttachmentCount     string    `json:"new_attachment_count,omitempty"`
	NewHasAttachment       string    `json:"new_has_attachment,omitempty"`
	NewFollower            string    `json:"new_follower,omitempty"`
	NewCreatedFrom         string    `json:"new_created_from,omitempty"`
	NewPredecessorCount    string    `json:"new_predecessor_count,omitempty"`
	NewSuccessorCount      string    `json:"new_successor_count,omitempty"`
	NewReleaseID           string    `json:"new_release_id,omitempty"`
	NewLabel               string    `json:"new_label,omitempty"`
	NewNewStoryID          string    `json:"new_new_story_id,omitempty"`
	ChangeFields           string    `json:"change_fields,omitempty"`
	Secret                 string    `json:"secret,omitempty"`
	RioToken               string    `json:"rio_token,omitempty"`
	DevProxyHost           string    `json:"devproxy_host,omitempty"`
	QueueID                string    `json:"queue_id,omitempty"`
	EventID                string    `json:"event_id,omitempty"`
	Created                string    `json:"created,omitempty"`
}

type TaskDeleteEvent struct {
	Event          EventType `json:"event,omitempty"`
	EventFrom      string    `json:"event_from,omitempty"`
	Referer        string    `json:"referer,omitempty"`
	WorkspaceID    string    `json:"workspace_id,omitempty"`
	CurrentUser    string    `json:"current_user,omitempty"`
	ID             string    `json:"id,omitempty"`
	OpType         string    `json:"op_type,omitempty"`
	OldIterationID string    `json:"old_iteration_id,omitempty"`
	Secret         string    `json:"secret,omitempty"`
	RioToken       string    `json:"rio_token,omitempty"`
	DevProxyHost   string    `json:"devproxy_host,omitempty"`
	QueueID        string    `json:"queue_id,omitempty"`
	EventID        string    `json:"event_id,omitempty"`
	Created        string    `json:"created,omitempty"`
}
